added scripts to find outliers in forms and analyze results
dimagi/rad-outlier-detect pull request #1
Opened 2021-03-23 15:23 UTC by faisalmlalani

Includes all the code written up to this point. Data and connection files are all left out.

2021-03-30 18:04 UTC, bderenzi reviewed
I left a bunch of comments. I didn't go through `run_outlier_detect` yet, but I think we talked about some of the methods there.

2021-03-30 18:16 UTC, faisalmlalani commented on db_connect.py
> +def connect_to_sql():
Sure, I agree with this. I think I mentioned this when we spoke, but my mindset in formatting this was to go for modularity and readability; even if the function or file would include a few lines, I justified it with the reasoning that in the future we might add more later. But even if that were the case, I could do this then.

I'll make this change.

2021-03-30 18:17 UTC, faisalmlalani commented on README
> +python3 run_outlier_detect.py --settings=settings.sample_settings
Right, this was just placeholder text. How should we go about the README? Describing our project? Using Ben's explanation?

2021-03-30 18:17 UTC, faisalmlalani commented on analyze_results.py
> +
Agreed.

I'll make this change.

2021-03-30 18:28 UTC, faisalmlalani commented on analyze_results.py
> +    ids = list(set(df[metric]))
Force of habit - I've always casted sets to lists since that structure is more familiar to me in case I need to modify it. For this use case, I agree.

I'll make this change.

2021-03-30 18:37 UTC, faisalmlalani commented on analyze_results.py
> +        average_scores.append({metric: i, score_key_string: average_score})
Do you mean something like:

`df_I.groupby('score', as_index=False).mean()`

2021-03-30 18:39 UTC, faisalmlalani commented on analyze_results.py
> +    forms = settings.FORMS
Before using simple settings, I put the string name and list of forms directly here. After adding that library, I just replaced those values. Agreed that it's redundant now.

I'll make this change.

2021-03-30 18:40 UTC, faisalmlalani commented on analyze_results.py
> +if __name__ == '__main__':
Sure, I actually do a similar thing. I copied this style from Ben's example.py code.

2021-03-30 18:45 UTC, faisalmlalani commented on analyze_results.py
> +            df_user_trends.drop('user_id', axis=1, inplace=True)
From what I understand, inplace just prevents the need to set the action to the df. so if I left it False by default, I'd need to do -

`df_user_trends = df_user_trends.drop('user_id', axis=1)`

which is just more consistent with what I've been doing elsewhere, hence your suggested change. Correct?

2021-03-30 18:46 UTC, faisalmlalani commented on analyze_results.py
> +            df_question_trends.to_csv(output_filename_questions)
I just blanked out some of the variables (like filenames) to make it more generalizable... if that makes sense. Like if you were to use this code but you named your files differently, you'd know to add it there.

2021-03-30 18:47 UTC, faisalmlalani commented on analyze_results.py
> +        while q <= number_of_quarters:
Thanks - these sorts of things really help! Always looking for ways to become a better programmer.

I'll make this change.

2021-03-30 18:48 UTC, faisalmlalani commented on analyze_results.py
> +                df_results = pd.read_csv(form_results_path)
Same reason as the filenames - I was just trying to make it more generalizable.

2021-03-30 18:49 UTC, faisalmlalani commented
@bderenzi thank you for going through this! Really appreciate it. I know you mentioned not going through run_outlier_detect.py, but I would appreciate some feedback there as well if you have time (no rush!).

I'll wait for some replies on the comments I made that don't end with "I'll make this change" before making the remaining changes and pushing another commit.

2021-03-30 20:42 UTC, bderenzi commented on analyze_results.py
> +            df_user_trends.drop('user_id', axis=1, inplace=True)
Yep, that's right.

I can't find it now, but Cory(?) sent me an article a while back where the author was talking about how one of the problems with pandas is that there are too many ways to do things. The point was made that one should be consistent and use methods that work in all cases. Can say more in a sync, but I think good for everyone, including future-you, to be consistent

2021-04-08 08:40 UTC, bderenzi commented on README
> +python3 run_outlier_detect.py --settings=settings.sample_settings
I think one or two  sentences focused on exactly what this repo does and then instructions for use so that someone can get it running on their machine

2021-04-08 08:41 UTC, bderenzi commented on .vscode/settings.json
> +}
Let's add `.vscode` to `.gitignore`. We shouldn't commit things like your python path to the repo. (Also, I strongly encourage you to use `virtualenv`)

2021-04-08 11:58 UTC, bderenzi commented on analyze_results.py
> +        average_scores.append({metric: i, score_key_string: average_score})
That is close to what I had in mind. I was thinking it would probably look like:

`df.groupby(metric).agg({'score':'mean'})`

You may need to filter before or after:

`df_i = df[df[metric].in(ids)]`

And you can then append the aggregated data frame (or parts of it) as before.

Does that achieve the same result? If yes, it's less code and more clear--and likely more performant.

2021-04-08 12:00 UTC, bderenzi commented on analyze_results.py
> +            df_question_trends.to_csv(output_filename_questions)
(assuming you'll make a plan)

2021-04-15 07:54 UTC, bderenzi commented on analyze_results.py
> +        median_score_key_string = 'median_score_' + str(q)
I think better to move the quarter to the front of the string so it is easier to see

2021-04-15 07:55 UTC, bderenzi commented on analyze_results.py
> +        median_score = np.median(df_i['score'])
Is there a shorter way to do this so it computes all in one go? I'm thinking something like the how you can do `df.groupby().agg(...)` and specify all the different aggregations you want to do. Maybe you can call `agg` directly?

2021-04-15 07:58 UTC, bderenzi commented on run_outlier_detect.py
> +    db = settings.DB
This is an odd variable name? It seems like this is actually the name of a separate annotations file? Doesn't seem like it is the 'db we want to connect to'

2021-04-15 07:58 UTC, bderenzi commented on run_outlier_detect.py
> +    forms = settings.FORMS
Why have a local variable if it is only ever used in the loop?

2021-04-15 08:01 UTC, bderenzi commented on run_outlier_detect.py
> +    return df
Again, this is a style thing, but we're writing 14 lines of code for what could ostensibly be one line of code since we don't reuse this anywhere. I can't think of where we'd need to do it. Why not just do `(df['completed_time'] - df['started_time'])/np.timedelta64(1, 's')` instead of where you call this function

2021-04-15 08:03 UTC, bderenzi requested changes
@faisalmlalani - I'm going to stop reviewing for now. I think there are still a number of pending comments. I added a few more. And some stuff we've already discussed. I think the next step is for you to take another passed based on the previous (and current) feedback. Doesn't seem like a great use of time to keep flagging the same things (e.g., the README, main function, getting rid of small functions, etc)

2021-04-15 17:24 UTC, faisalmlalani commented on .vscode/settings.json
> +}
Using virtualenv now! Thanks for the suggestion.

2021-04-15 17:54 UTC, faisalmlalani commented on run_outlier_detect.py
> +    db = settings.DB
Change made!

2021-04-15 17:54 UTC, faisalmlalani commented on run_outlier_detect.py
> +    forms = settings.FORMS
Removed!

2021-04-15 17:56 UTC, faisalmlalani commented on run_outlier_detect.py
> +    return df
It's just my tendency to modularize (admittedly to the extreme) in the chance that the purpose of the function will be elaborated upon in the future. I agree to keep it short and sweet for now though. Made the change.

2021-04-16 07:17 UTC, bderenzi commented on run_outlier_detect.py
> +    db = settings.DB
Cool. And, just to say I'm going to ignore until you reopen / request a review again. And, expecting you'll push the changes to this branch before that so that the PR updates. Are there maybe a number of changes you've made that haven't been pushed to this branch yet?

2021-06-11 09:30 UTC, bderenzi commented
Is this pull request no longer valid? It seems like it was abandoned. If that's the case, can we close it?

2021-06-14 15:26 UTC, closed without merging